### ISSUE TITLE
Class-based views methods

### ISSUE THREAD

**Issue by emerline-pavelsushko** [KarimKkhalifa/LeverX_task5#4]
https://github.com/KarimKkhalifa/LeverX_task5/blob/5631652d6507ff2662889559001c239a9f47b77e/online_courses/views.py#L52

When using class-based views you can re-implement internal methods like `get_queryset()` so you can separate object retrieval process and don't need to explicitly return Response with 404 code.

**Comment by KarimKkhalifa** [comment]
remade views and added get_queryset() method
